### ISSUE TITLE
编码问题报错

### ISSUE THREAD

**Issue by Albertchamberlain** [popolyj/DailyPaper#2]
1-19日问题

2020-01-19 14:03:00,772 - DailyPaper - ERROR - Utils  - 134 - 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

编码问题继续报错

**Comment by popolyj** [comment]
检查下Config.ini文件的编码，如果是历史版本可能会出现这个问题，请确保文件是utf-8的格式

**Comment by Albertchamberlain** [comment]
文件确定是utf-8格式

**Comment by popolyj** [comment]
你的代码是什么时候更新的？

**Comment by Albertchamberlain** [comment]
今天下午，clone你的项目

**Comment by popolyj** [comment]
你本地python的版本是多少？

**Comment by Albertchamberlain** [comment]
python3.6

**Comment by popolyj** [comment]
3.6的版本可能会出现问题，最低版本要求3.7.3

**Comment by Albertchamberlain** [comment]
好的，收到

**Comment by popolyj** [comment]
新的可视化版本更新了，你可以去论坛看看

**Comment by Albertchamberlain** [comment]
哈哈哈，咱们既然去了github，就是研究源码的😁



---原始邮件---
发件人: "圣殿治愈者"<notifications@github.com&gt;
发送时间: 2020年1月20日(周一) 晚上11:00
收件人: "popolyj/DailyPaper"<DailyPaper@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Amos Albert"<2476271447@qq.com&gt;;
主题: Re: [popolyj/DailyPaper] 编码问题报错 (#2)



新的可视化版本更新了，你可以去论坛看看
